version: '3'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/src
    ports:
      - 8443:8443

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
  mem-db:
    image: redis
    ports:
      - "6379:6379"