version: '3'
services:

  api:
    image: 541866003555.dkr.ecr.us-east-1.amazonaws.com/globo-challenge/api:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/src
    ports:
      - 9443:8443

  front:
    image: 541866003555.dkr.ecr.us-east-1.amazonaws.com/globo-challenge/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: ["nginx", "-g", "daemon off;"]
    ports:
      - 9080:80

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db

  mem-db:
    image: redis
    ports:
      - "6379:6379"