- hosts: all
  remote_user: centos
  gather_facts: no
  tasks:
    - include: ../install-docker/tasks.yml
    - include: ../install-docker-compose/tasks.yml
    - include: ../install-aws-cli/tasks.yml
    - include: ../install-aws-credentials/tasks.yml
    - include: tasks.yml
    - include: ../deploy-api/tasks.yml

