version: '3'
services:

  api:
    image: 541866003555.dkr.ecr.us-east-1.amazonaws.com/globo-challenge/api:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 9443:8443
    command: ["java", "-Xms5G", "-Xmx5G", "-jar", "/run/server.jar"]