- name: get docker compose
  remote_user: centos
  become: yes
  become_method: sudo
  command: bash -c 'sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'

- name: docker-compose globally
  remote_user: centos
  become: yes
  become_method: sudo
  command: bash -c 'ln -fs /usr/local/bin/docker-compose /bin/docker-compose && chmod +x /usr/local/bin/docker-compose'
